title: Steff Wedding
tagline: Сватбени Рокли и Организация
description: Steff Wedding е луксозен сватбен бутик, който носи неподражаемия дух на бохо, винтидж и ръстик елементите за една
  незабравима сватба с твоя личен почерк!
url: https://steffwedding.com
logo: /assets/logo.svg
social:
  name: Steff Wedding – Сватбени Рокли и Организация
  links:
    - https://facebook.com/Steff.Wedding
    - https://instagram.com/steff.wedding
locale: bg_BG

# Build settings
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier

sass:
  sass_dir: _sass
  style: compact

collections:
  sw-collections:
    output: true
    permalink: /collections/:name

  sw-dresses:
    output: true
    permalink: /dresses/:name

jekyll-minifier:
  compress_css: true
  compress_javascript: true
  compress_json: true
  uglifier_args:
    harmony: true
