title: Steff Wedding – Сватбени Рокли и Организация

# Build settings
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compact

collections:
  collections:
    output: true

  dresses:
    output: true