title: Steff Wedding – Сватбени Рокли и Организация

# Build settings
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compact

collections:
  sw-collections:
    output: true
    permalink: /collections/:name

  sw-dresses:
    output: true
    permalink: /dresses/:name
